### ISSUE TITLE
from vision.references.detection import utils ModuleNotFoundError: No module named 'vision'

### ISSUE THREAD

**Issue by prem2279** [Aditya239233/Pedestrian-Segmentation#1]
import torchvision
from vision.references.detection import utils
import vision.references.detection.transforms as T

def get_transform(train):
    # data augmentation
    transforms = []
    transforms.append(T.ToTensor())

    if train:
        transforms.append(T.RandomHorizontalFlip(0.5))
    
    return T.Compose(transforms)

def add_pallet(mask):
    mask.putpalette([
    0, 0, 0, # black background
    255, 0, 0, # index 1 is red
    255, 255, 0, # index 2 is yellow
    255, 153, 0, # index 3 is orange
    ])
    return mask

def collate_fn(batch):
    return tuple(zip(*batch))

error i am getting is
Traceback (most recent call last):
  File "D:\MINI PROJECT\Pedestrian-Segmentation-main\src\helper.py", line 2, in <module>
    from vision.references.detection import utils
ModuleNotFoundError: No module named 'vision'

**Comment by Aditya239233** [comment]
Try doing the following commands to fix this issue:
``` bash
git clone https://github.com/pytorch/vision.git
cd vision
git checkout v0.3.0

cp references/detection/utils.py ../
cp references/detection/transforms.py ../
cp references/detection/coco_eval.py ../
cp references/detection/engine.py ../
cp references/detection/coco_utils.py ../
```

**Comment by prem2279** [comment]
thanks 
its working now
