### ISSUE TITLE
why cant i use this code for predicting images other than dataset images

### ISSUE THREAD

**Issue by prem2279** [Aditya239233/Pedestrian-Segmentation#3]
when i tested this code on other images , other than dataset images,it is not predicting
what is the main reason for this?

**Comment by Aditya239233** [comment]
Can you elaborate more on this?

**Comment by prem2279** [comment]
@Aditya239233   **In predictsegmentation.py**
when i upload the image from the  Penn-Fudan Dataset ,I am getting segmentation correctly like below

![Screenshot 2021-03-19 164244](https://user-images.githubusercontent.com/60621227/111772389-cc7a2a00-88d2-11eb-9606-21ccd2b96323.png)

when i run the code for an image which i have dowloaded from the net, the segmentation is not happening ,it is showing the blank image like below

![Screenshot 2021-03-19 163704](https://user-images.githubusercontent.com/60621227/111772645-182cd380-88d3-11eb-9c36-5db033d2d0cd.png)

The code is only working for the images in the  Penn-Fudan Dataset, but when i run the code on images other than the  Penn-Fudan Dataset it is not working.
**What  is the main reason for it?**
